// 畑めぐり（rinsaku-planner）— 家庭菜園 作物マスタ（連作・輪作データセット）。
// 本州/中間地基準の代表値。サカタのタネ / タキイ種苗 / 農林水産省 / JA / 園芸メディアを
// 横断確認して採った値で、地域・品種・栽培様式で前後する。製品の moat となるデータ層。
//
// rotationYears: 同じ「科」を同じ場所に再び植えるまであける目安年数（0 = 連作障害が出にくい）。
//   ※連作判定は「科」単位（familyKey が一致する過去作付け）で行う。
// sowMonths / harvestMonths: 1–12 の月。種まき/植え付け、収穫の代表的な時期。
// companionGood / companionBad: 相性。科ではなく「作物ごと」に保持する
//   （マメ科はネギ亜科とは相性が悪く、オクラ/サトイモとは相性が良い等、科一律にできないため）。

/**
 * @typedef {import("./types").Family} Family
 * @typedef {import("./types").Crop} Crop
 */

/** 科の一覧（rotationYears はその科の代表値）。 */
export const FAMILIES = /** @type {Family[]} */ ([
  { key: "solanaceae", nameJa: "ナス科", rotationYears: 4 },
  { key: "cucurbitaceae", nameJa: "ウリ科", rotationYears: 3 },
  { key: "brassicaceae", nameJa: "アブラナ科", rotationYears: 2 },
  { key: "fabaceae", nameJa: "マメ科", rotationYears: 3 },
  { key: "apiaceae", nameJa: "セリ科", rotationYears: 2 },
  { key: "asteraceae", nameJa: "キク科", rotationYears: 2 },
  { key: "amaranthaceae", nameJa: "ヒユ科", rotationYears: 1 },
  { key: "convolvulaceae", nameJa: "ヒルガオ科", rotationYears: 0 },
  { key: "poaceae", nameJa: "イネ科", rotationYears: 0 },
  { key: "allium", nameJa: "ヒガンバナ科（ネギ類）", rotationYears: 1 },
  { key: "zingiberaceae", nameJa: "ショウガ科", rotationYears: 4 },
  { key: "araceae", nameJa: "サトイモ科", rotationYears: 4 },
  { key: "malvaceae", nameJa: "アオイ科", rotationYears: 2 },
  { key: "rosaceae", nameJa: "バラ科", rotationYears: 2 },
  { key: "lamiaceae", nameJa: "シソ科", rotationYears: 1 },
]);

/** 作物マスタ（科でまとめて記載）。 */
export const CROPS = /** @type {Crop[]} */ ([
  // ===== ナス科 =====
  {
    id: "tomato",
    nameJa: "トマト",
    familyJa: "ナス科",
    familyKey: "solanaceae",
    rotationYears: 4,
    sowMonths: [4, 5],
    harvestMonths: [6, 7, 8, 9],
    companionGood: [
      "バジル",
      "ニラ",
      "ネギ",
      "マリーゴールド",
      "ラッカセイ",
      "パセリ",
    ],
    companionBad: [
      "ナス",
      "ピーマン",
      "ジャガイモ",
      "キュウリ",
      "トウモロコシ",
    ],
    note: "ナス科。連作を避け4年あける。ニラ・ネギ混植で土壌病害を予防",
  },
  {
    id: "mini-tomato",
    nameJa: "ミニトマト",
    familyJa: "ナス科",
    familyKey: "solanaceae",
    rotationYears: 4,
    sowMonths: [4, 5],
    harvestMonths: [6, 7, 8, 9],
    companionGood: ["バジル", "ニラ", "ネギ", "マリーゴールド", "ラッカセイ"],
    companionBad: ["ナス", "ピーマン", "ジャガイモ", "キュウリ"],
    note: "トマトと同栽培。連作は4年あける",
  },
  {
    id: "eggplant",
    nameJa: "ナス",
    familyJa: "ナス科",
    familyKey: "solanaceae",
    rotationYears: 4,
    sowMonths: [5],
    harvestMonths: [6, 7, 8, 9, 10],
    companionGood: [
      "ニラ",
      "ラッカセイ",
      "ショウガ",
      "パセリ",
      "マリーゴールド",
    ],
    companionBad: ["トマト", "ピーマン", "ジャガイモ", "キュウリ"],
    note: "ナス科の連作障害が出やすい筆頭。ニラ混植で青枯病予防、4年あける",
  },
  {
    id: "bell-pepper",
    nameJa: "ピーマン",
    familyJa: "ナス科",
    familyKey: "solanaceae",
    rotationYears: 4,
    sowMonths: [5],
    harvestMonths: [7, 8, 9, 10],
    companionGood: ["ニラ", "ラッカセイ", "マリーゴールド", "ネギ"],
    companionBad: ["ナス", "トマト", "ジャガイモ"],
    note: "ナス科。ニラ・ラッカセイ混植で病害とセンチュウを抑制",
  },
  {
    id: "shishito",
    nameJa: "シシトウ",
    familyJa: "ナス科",
    familyKey: "solanaceae",
    rotationYears: 4,
    sowMonths: [5],
    harvestMonths: [6, 7, 8, 9, 10],
    companionGood: ["ニラ", "ラッカセイ", "マリーゴールド"],
    companionBad: ["ナス", "トマト", "ピーマン", "ジャガイモ"],
    note: "ナス科。ピーマンに準じ4年あける",
  },
  {
    id: "chili-pepper",
    nameJa: "トウガラシ",
    familyJa: "ナス科",
    familyKey: "solanaceae",
    rotationYears: 4,
    sowMonths: [5],
    harvestMonths: [7, 8, 9, 10],
    companionGood: ["ニラ", "ラッカセイ", "マリーゴールド"],
    companionBad: ["ナス", "トマト", "ピーマン", "ジャガイモ"],
    note: "ナス科トウガラシ属。シシトウと同管理で4年あける",
  },
  {
    id: "potato",
    nameJa: "ジャガイモ",
    familyJa: "ナス科",
    familyKey: "solanaceae",
    rotationYears: 3,
    sowMonths: [2, 3, 9],
    harvestMonths: [6, 7, 11, 12],
    companionGood: ["ネギ", "マリーゴールド", "インゲン"],
    companionBad: ["トマト", "ナス", "ピーマン", "キュウリ"],
    note: "ナス科だが連作年限はやや短い2〜3年。ソウカ病に注意",
  },

  // ===== ウリ科 =====
  {
    id: "cucumber",
    nameJa: "キュウリ",
    familyJa: "ウリ科",
    familyKey: "cucurbitaceae",
    rotationYears: 3,
    sowMonths: [4, 5],
    harvestMonths: [6, 7, 8, 9],
    companionGood: ["ネギ", "ニラ", "マリーゴールド"],
    companionBad: ["カボチャ", "スイカ", "ジャガイモ"],
    note: "連作は2〜3年あける。ネギ・ニラ混植でつる割病を抑制",
  },
  {
    id: "pumpkin",
    nameJa: "カボチャ",
    familyJa: "ウリ科",
    familyKey: "cucurbitaceae",
    rotationYears: 1,
    sowMonths: [4, 5],
    harvestMonths: [7, 8, 9],
    companionGood: ["ネギ", "トウモロコシ", "エダマメ"],
    companionBad: ["キュウリ", "スイカ", "ジャガイモ"],
    note: "ウリ科では連作障害が少ない。ネギ混植でつるぼけ防止",
  },
  {
    id: "zucchini",
    nameJa: "ズッキーニ",
    familyJa: "ウリ科",
    familyKey: "cucurbitaceae",
    rotationYears: 2,
    sowMonths: [3, 4],
    harvestMonths: [6, 7, 8],
    companionGood: ["ネギ", "タマネギ", "ニンニク"],
    companionBad: ["キュウリ", "カボチャ", "スイカ"],
    note: "比較的連作に強いが、ウリ科の連作は避ける",
  },
  {
    id: "watermelon",
    nameJa: "スイカ",
    familyJa: "ウリ科",
    familyKey: "cucurbitaceae",
    rotationYears: 5,
    sowMonths: [3, 4, 5],
    harvestMonths: [7, 8, 9],
    companionGood: ["ネギ", "ニラ", "マリーゴールド", "トウモロコシ"],
    companionBad: ["キュウリ", "カボチャ", "メロン"],
    note: "連作を極度に嫌い5年ほどあける。接ぎ木苗でつる割病回避",
  },
  {
    id: "melon",
    nameJa: "メロン",
    familyJa: "ウリ科",
    familyKey: "cucurbitaceae",
    rotationYears: 4,
    sowMonths: [3, 4],
    harvestMonths: [8],
    companionGood: ["ネギ", "マリーゴールド"],
    companionBad: ["キュウリ", "スイカ", "カボチャ"],
    note: "連作障害が出やすく3〜5年あける。ネギ混植が有効",
  },
  {
    id: "bitter-melon",
    nameJa: "ゴーヤ",
    familyJa: "ウリ科",
    familyKey: "cucurbitaceae",
    rotationYears: 3,
    sowMonths: [3, 4, 5],
    harvestMonths: [7, 8, 9],
    companionGood: ["ネギ", "タマネギ", "トウモロコシ"],
    companionBad: ["キュウリ", "カボチャ", "スイカ"],
    note: "連作は2〜3年あける。ネギ類でつる割病・ウリハムシ抑制",
  },
  {
    id: "winter-melon",
    nameJa: "トウガン",
    familyJa: "ウリ科",
    familyKey: "cucurbitaceae",
    rotationYears: 3,
    sowMonths: [3, 4],
    harvestMonths: [8, 9],
    companionGood: ["ネギ", "ニラ"],
    companionBad: ["キュウリ", "カボチャ", "スイカ"],
    note: "ウリ科で連作障害あり3年ほどあける。摘心で着果促進",
  },

  // ===== アブラナ科 =====
  {
    id: "cabbage",
    nameJa: "キャベツ",
    familyJa: "アブラナ科",
    familyKey: "brassicaceae",
    rotationYears: 2,
    sowMonths: [3, 4, 8, 9],
    harvestMonths: [6, 7, 8, 11, 12],
    companionGood: ["レタス", "シュンギク", "ソラマメ", "ニンニク"],
    companionBad: ["ハクサイ", "ブロッコリー", "ダイコン"],
    note: "根こぶ病に注意。アブラナ科連作を避け2〜3年あける",
  },
  {
    id: "broccoli",
    nameJa: "ブロッコリー",
    familyJa: "アブラナ科",
    familyKey: "brassicaceae",
    rotationYears: 2,
    sowMonths: [2, 3, 7, 8],
    harvestMonths: [5, 6, 11, 12, 1, 2],
    companionGood: ["レタス", "シュンギク", "ソラマメ"],
    companionBad: ["キャベツ", "ハクサイ", "ダイコン", "カブ"],
    note: "レタス・春菊と混植で防虫。連作は2〜3年あける",
  },
  {
    id: "cauliflower",
    nameJa: "カリフラワー",
    familyJa: "アブラナ科",
    familyKey: "brassicaceae",
    rotationYears: 2,
    sowMonths: [2, 3, 7, 8],
    harvestMonths: [5, 6, 11, 12, 1, 2],
    companionGood: ["レタス", "シュンギク"],
    companionBad: ["キャベツ", "ブロッコリー", "ハクサイ", "ダイコン"],
    note: "レタスと交互植えで防虫。2〜3年あける",
  },
  {
    id: "chinese-cabbage",
    nameJa: "ハクサイ",
    familyJa: "アブラナ科",
    familyKey: "brassicaceae",
    rotationYears: 2,
    sowMonths: [8, 9],
    harvestMonths: [11, 12, 1, 2],
    companionGood: ["レタス", "シュンギク", "マリーゴールド"],
    companionBad: ["キャベツ", "ブロッコリー", "ダイコン", "カブ"],
    note: "アオムシ・アブラムシ多。根こぶ病に注意し2〜3年あける",
  },
  {
    id: "daikon-radish",
    nameJa: "ダイコン",
    familyJa: "アブラナ科",
    familyKey: "brassicaceae",
    rotationYears: 2,
    sowMonths: [3, 4, 5, 8, 9],
    harvestMonths: [6, 7, 10, 11, 12],
    companionGood: ["マリーゴールド", "ルッコラ", "ニンジン"],
    companionBad: ["キャベツ", "ハクサイ", "ブロッコリー", "カブ"],
    note: "萎黄病・根こぶ病対策で2〜3年あける。直根性で移植不可",
  },
  {
    id: "turnip",
    nameJa: "カブ",
    familyJa: "アブラナ科",
    familyKey: "brassicaceae",
    rotationYears: 2,
    sowMonths: [3, 4, 5, 8, 9],
    harvestMonths: [5, 6, 10, 11, 12],
    companionGood: ["レタス", "シュンギク", "ネギ"],
    companionBad: ["ハクサイ", "ダイコン", "キャベツ", "ブロッコリー"],
    note: "根こぶ病に注意。連作は1〜2年あける（病害圃場はより長く）",
  },
  {
    id: "komatsuna",
    nameJa: "コマツナ",
    familyJa: "アブラナ科",
    familyKey: "brassicaceae",
    rotationYears: 1,
    sowMonths: [3, 4, 5, 9, 10],
    harvestMonths: [4, 5, 6, 10, 11, 12],
    companionGood: ["レタス", "シュンギク", "ニラ", "ニンジン"],
    companionBad: ["ハクサイ", "カブ", "ダイコン", "ミズナ"],
    note: "連作は1〜2年あける。キク科・ニラ混植で防虫",
  },
  {
    id: "mizuna",
    nameJa: "ミズナ",
    familyJa: "アブラナ科",
    familyKey: "brassicaceae",
    rotationYears: 1,
    sowMonths: [4, 5, 9, 10],
    harvestMonths: [5, 6, 10, 11, 12],
    companionGood: ["レタス", "シュンギク", "ニンジン"],
    companionBad: ["ダイコン", "チンゲンサイ", "ハクサイ", "ブロッコリー"],
    note: "連作は1〜2年あける。アブラナ科連作で生育不良",
  },
  {
    id: "bok-choy",
    nameJa: "チンゲンサイ",
    familyJa: "アブラナ科",
    familyKey: "brassicaceae",
    rotationYears: 1,
    sowMonths: [3, 4, 5, 8, 9, 10],
    harvestMonths: [4, 5, 6, 10, 11, 12],
    companionGood: ["シュンギク", "レタス", "マリーゴールド"],
    companionBad: ["ハクサイ", "ミズナ", "ダイコン", "コマツナ"],
    note: "連作は1〜2年あける。春菊との混植で害虫忌避",
  },
  {
    id: "radish",
    nameJa: "ラディッシュ",
    familyJa: "アブラナ科",
    familyKey: "brassicaceae",
    rotationYears: 2,
    sowMonths: [3, 4, 5, 9, 10],
    harvestMonths: [4, 5, 6, 10, 11],
    companionGood: ["シュンギク", "レタス", "ニンジン", "バジル"],
    companionBad: ["ダイコン", "カブ", "ハクサイ", "コマツナ"],
    note: "二十日大根。連作障害に注意しバジル混植で軽減",
  },
  {
    id: "arugula",
    nameJa: "ルッコラ",
    familyJa: "アブラナ科",
    familyKey: "brassicaceae",
    rotationYears: 1,
    sowMonths: [4, 5, 6, 7, 9, 10],
    harvestMonths: [5, 6, 7, 8, 10, 11, 12],
    companionGood: ["レタス", "シュンギク", "トマト", "ナス"],
    companionBad: ["ダイコン", "ハクサイ", "キャベツ", "コマツナ"],
    note: "アブラムシ忌避効果あり。連作は1〜2年あける",
  },
  {
    id: "kale",
    nameJa: "ケール",
    familyJa: "アブラナ科",
    familyKey: "brassicaceae",
    rotationYears: 2,
    sowMonths: [3, 4, 8, 9],
    harvestMonths: [5, 6, 7, 11, 12, 1, 2],
    companionGood: ["レタス", "シュンギク", "ソラマメ"],
    companionBad: ["キャベツ", "ブロッコリー", "ハクサイ", "ダイコン"],
    note: "外葉から長期収穫。連作は1〜2年あけ防虫ネット推奨",
  },

  // ===== マメ科 =====
  {
    id: "edamame",
    nameJa: "エダマメ",
    familyJa: "マメ科",
    familyKey: "fabaceae",
    rotationYears: 3,
    sowMonths: [4, 5],
    harvestMonths: [7, 8],
    companionGood: ["トウモロコシ", "ニンジン", "カボチャ", "キュウリ"],
    companionBad: ["ネギ", "タマネギ", "ニラ"],
    note: "連作は2〜4年あける。ネギ類は根粒菌を阻害し混植不可",
  },
  {
    id: "green-bean",
    nameJa: "インゲン",
    familyJa: "マメ科",
    familyKey: "fabaceae",
    rotationYears: 3,
    sowMonths: [5, 6],
    harvestMonths: [7, 8, 9],
    companionGood: ["マリーゴールド", "トウモロコシ", "ニンジン", "セロリ"],
    companionBad: ["ネギ", "タマネギ", "ニラ"],
    note: "連作障害が出やすく3年あける。マリーゴールドでセンチュウ抑制",
  },
  {
    id: "pea",
    nameJa: "エンドウ",
    familyJa: "マメ科",
    familyKey: "fabaceae",
    rotationYears: 5,
    sowMonths: [10, 11],
    harvestMonths: [4, 5, 6],
    companionGood: ["ホウレンソウ", "コマツナ", "パセリ"],
    companionBad: ["ネギ", "タマネギ", "ニラ"],
    note: "マメ科で最も連作に弱く4〜5年あける。秋まき翌春収穫",
  },
  {
    id: "broad-bean",
    nameJa: "ソラマメ",
    familyJa: "マメ科",
    familyKey: "fabaceae",
    rotationYears: 4,
    sowMonths: [10, 11],
    harvestMonths: [5, 6],
    companionGood: ["タマネギ", "ニンニク"],
    companionBad: ["インゲン", "エンドウ"],
    note: "連作で3〜5年あける。例外的にタマネギ・ニンニク混植が有効",
  },
  {
    id: "peanut",
    nameJa: "ラッカセイ",
    familyJa: "マメ科",
    familyKey: "fabaceae",
    rotationYears: 2,
    sowMonths: [5, 6],
    harvestMonths: [10, 11],
    companionGood: ["トマト", "ナス", "ピーマン"],
    companionBad: ["ネギ", "タマネギ"],
    note: "マメ科では連作に比較的強く2〜3年が目安",
  },

  // ===== セリ科 =====
  {
    id: "carrot",
    nameJa: "ニンジン",
    familyJa: "セリ科",
    familyKey: "apiaceae",
    rotationYears: 2,
    sowMonths: [3, 4, 7, 8],
    harvestMonths: [7, 8, 11, 12],
    companionGood: ["エダマメ", "ダイコン", "カブ", "ニラ", "コマツナ"],
    companionBad: ["インゲン", "ミツバ", "パセリ", "セロリ"],
    note: "連作障害は1〜2年と短め。同じセリ科の混植は避ける",
  },
  {
    id: "parsley",
    nameJa: "パセリ",
    familyJa: "セリ科",
    familyKey: "apiaceae",
    rotationYears: 1,
    sowMonths: [4, 5, 9, 10],
    harvestMonths: [6, 7, 8, 9, 10, 11],
    companionGood: ["トマト", "ナス", "エンドウ"],
    companionBad: ["ニンジン", "ミツバ", "セロリ", "パクチー"],
    note: "連作障害は弱いが1〜2年。半日陰OK。株元コンパニオンに好適",
  },
  {
    id: "celery",
    nameJa: "セロリ",
    familyJa: "セリ科",
    familyKey: "apiaceae",
    rotationYears: 2,
    sowMonths: [5, 6],
    harvestMonths: [11, 12],
    companionGood: ["インゲン", "トマト", "キャベツ"],
    companionBad: ["ニンジン", "ミツバ", "パセリ", "パクチー"],
    note: "連作は2〜3年あける。春まき秋冬どりが家庭菜園では一般的",
  },
  {
    id: "mitsuba",
    nameJa: "ミツバ",
    familyJa: "セリ科",
    familyKey: "apiaceae",
    rotationYears: 2,
    sowMonths: [4, 5, 9, 10],
    harvestMonths: [5, 6, 7, 10, 11, 12],
    companionGood: ["ニンジン"],
    companionBad: ["パセリ", "セロリ", "パクチー"],
    note: "セリ科跡地は1〜2年あける。半日陰・冷涼を好む。再生栽培可",
  },
  {
    id: "coriander",
    nameJa: "パクチー",
    familyJa: "セリ科",
    familyKey: "apiaceae",
    rotationYears: 1,
    sowMonths: [4, 5, 9, 10],
    harvestMonths: [6, 7, 10, 11],
    companionGood: ["トマト", "ナス", "キャベツ"],
    companionBad: ["ニンジン", "ミツバ", "セロリ", "パセリ"],
    note: "セリ科連作は1〜2年回避。強い香りでアブラムシ等を忌避",
  },

  // ===== キク科 =====
  {
    id: "lettuce",
    nameJa: "レタス",
    familyJa: "キク科",
    familyKey: "asteraceae",
    rotationYears: 2,
    sowMonths: [3, 4, 5, 8, 9, 10],
    harvestMonths: [5, 6, 10, 11],
    companionGood: ["ブロッコリー", "キャベツ", "ハクサイ", "ニンジン"],
    companionBad: ["ネギ", "ニラ"],
    note: "キク科×アブラナ科で害虫を抑制。連作は2年あける",
  },
  {
    id: "sunny-lettuce",
    nameJa: "サニーレタス",
    familyJa: "キク科",
    familyKey: "asteraceae",
    rotationYears: 2,
    sowMonths: [3, 4, 5, 8, 9, 10],
    harvestMonths: [5, 6, 10, 11],
    companionGood: ["ブロッコリー", "キャベツ", "ルッコラ", "ニンジン"],
    companionBad: ["ネギ", "ニラ"],
    note: "結球しない分育てやすい。連作は2年あける",
  },
  {
    id: "shungiku",
    nameJa: "シュンギク",
    familyJa: "キク科",
    familyKey: "asteraceae",
    rotationYears: 1,
    sowMonths: [4, 5, 9, 10],
    harvestMonths: [5, 6, 10, 11, 12],
    companionGood: ["ハクサイ", "キャベツ", "ダイコン", "カブ", "チンゲンサイ"],
    companionBad: [],
    note: "アブラナ科の害虫忌避に有効。連作障害は比較的軽い",
  },
  {
    id: "burdock",
    nameJa: "ゴボウ",
    familyJa: "キク科",
    familyKey: "asteraceae",
    rotationYears: 5,
    sowMonths: [3, 4, 5],
    harvestMonths: [10, 11, 12],
    companionGood: ["ホウレンソウ"],
    companionBad: ["ニンジン", "ナス", "トマト"],
    note: "連作障害が強く4〜5年あける。センチュウ被害に注意",
  },

  // ===== ヒユ科 =====
  {
    id: "spinach",
    nameJa: "ホウレンソウ",
    familyJa: "ヒユ科",
    familyKey: "amaranthaceae",
    rotationYears: 1,
    sowMonths: [4, 5, 9, 10],
    harvestMonths: [5, 6, 10, 11, 12, 1, 2],
    companionGood: ["ネギ", "ニンジン", "ゴボウ"],
    companionBad: [],
    note: "ネギ類が萎凋病を抑制。連作は1〜2年あける",
  },
  {
    id: "swiss-chard",
    nameJa: "フダンソウ",
    familyJa: "ヒユ科",
    familyKey: "amaranthaceae",
    rotationYears: 1,
    sowMonths: [4, 5, 6, 7, 8, 9],
    harvestMonths: [5, 6, 7, 8, 9, 10, 11],
    companionGood: ["ネギ", "マリーゴールド"],
    companionBad: [],
    note: "暑さ寒さに強く長期収穫可（スイスチャード）。連作は1〜2年あける",
  },
  {
    id: "beet",
    nameJa: "ビーツ",
    familyJa: "ヒユ科",
    familyKey: "amaranthaceae",
    rotationYears: 1,
    sowMonths: [3, 4, 8, 9],
    harvestMonths: [6, 7, 10, 11],
    companionGood: ["マリーゴールド", "ネギ", "ニラ", "キャベツ"],
    companionBad: [],
    note: "種は吸水処理で発芽向上。連作は1〜2年あける",
  },

  // ===== ヒルガオ科 =====
  {
    id: "sweet-potato",
    nameJa: "サツマイモ",
    familyJa: "ヒルガオ科",
    familyKey: "convolvulaceae",
    rotationYears: 0,
    sowMonths: [5, 6],
    harvestMonths: [9, 10, 11],
    companionGood: ["エダマメ", "ラッカセイ", "シソ"],
    companionBad: [],
    note: "連作障害がほぼ無く連作向き。やせ地向き・挿し苗で植付け",
  },

  // ===== イネ科 =====
  {
    id: "corn",
    nameJa: "トウモロコシ",
    familyJa: "イネ科",
    familyKey: "poaceae",
    rotationYears: 0,
    sowMonths: [4, 5],
    harvestMonths: [7, 8],
    companionGood: ["エダマメ", "インゲン", "カボチャ"],
    companionBad: ["トマト", "ナス", "ピーマン"],
    note: "連作障害が少なく連作可。マメ科・カボチャと三姉妹植え",
  },

  // ===== ヒガンバナ科（ネギ類） =====
  {
    id: "green-onion",
    nameJa: "ネギ",
    familyJa: "ヒガンバナ科（ネギ類）",
    familyKey: "allium",
    rotationYears: 0,
    sowMonths: [3, 4],
    harvestMonths: [11, 12, 1, 2],
    companionGood: ["トマト", "ナス", "キュウリ", "スイカ"],
    companionBad: ["インゲン", "エダマメ", "エンドウ"],
    note: "連作向き。ウリ科・ナス科の土壌病害を抑えるコンパニオン",
  },
  {
    id: "onion",
    nameJa: "タマネギ",
    familyJa: "ヒガンバナ科（ネギ類）",
    familyKey: "allium",
    rotationYears: 1,
    sowMonths: [9, 11],
    harvestMonths: [5, 6],
    companionGood: ["カモミール", "ホウレンソウ", "イチゴ"],
    companionBad: ["インゲン", "エダマメ", "エンドウ"],
    note: "連作障害は出にくいが1年あけると安心。苗植え11月→翌5〜6月",
  },
  {
    id: "garlic",
    nameJa: "ニンニク",
    familyJa: "ヒガンバナ科（ネギ類）",
    familyKey: "allium",
    rotationYears: 1,
    sowMonths: [9, 10],
    harvestMonths: [6],
    companionGood: ["イチゴ", "キュウリ", "トマト", "ナス"],
    companionBad: ["インゲン", "エダマメ"],
    note: "連作障害は出にくいが3年以上の連作で土壌病害リスク増",
  },
  {
    id: "chinese-chive",
    nameJa: "ニラ",
    familyJa: "ヒガンバナ科（ネギ類）",
    familyKey: "allium",
    rotationYears: 0,
    sowMonths: [3, 4],
    harvestMonths: [4, 5, 6, 7, 8, 9, 10],
    companionGood: ["トマト", "ナス", "ピーマン", "キュウリ"],
    companionBad: ["インゲン", "エダマメ"],
    note: "多年草で数年収穫可。連作向きで他作物の病害も抑制",
  },
  {
    id: "rakkyo",
    nameJa: "ラッキョウ",
    familyJa: "ヒガンバナ科（ネギ類）",
    familyKey: "allium",
    rotationYears: 1,
    sowMonths: [8, 9],
    harvestMonths: [6],
    companionGood: ["トマト", "ナス", "キュウリ"],
    companionBad: ["インゲン", "エダマメ"],
    note: "連作障害は出にくいがネギ類の後作は避ける",
  },
  {
    id: "chives",
    nameJa: "アサツキ",
    familyJa: "ヒガンバナ科（ネギ類）",
    familyKey: "allium",
    rotationYears: 1,
    sowMonths: [8, 9],
    harvestMonths: [10, 11, 3, 4],
    companionGood: ["キュウリ", "トマト", "ナス", "ホウレンソウ"],
    companionBad: ["インゲン", "エダマメ"],
    note: "種球を夏に植え秋と春に収穫。病気予防で間隔をあける",
  },

  // ===== ショウガ科 =====
  {
    id: "ginger",
    nameJa: "ショウガ",
    familyJa: "ショウガ科",
    familyKey: "zingiberaceae",
    rotationYears: 4,
    sowMonths: [4, 5],
    harvestMonths: [8, 9, 10, 11],
    companionGood: ["ナス", "サトイモ"],
    companionBad: ["ジャガイモ"],
    note: "連作障害が強く4〜5年あける。半日陰と水分を好む",
  },
  {
    id: "myoga",
    nameJa: "ミョウガ",
    familyJa: "ショウガ科",
    familyKey: "zingiberaceae",
    rotationYears: 1,
    sowMonths: [3, 4],
    harvestMonths: [7, 8, 9, 10],
    companionGood: ["ミツバ", "ニラ", "パセリ"],
    companionBad: [],
    note: "多年草で同じ場所を数年栽培可。植え替え時は場所を変える",
  },

  // ===== サトイモ科 =====
  {
    id: "taro",
    nameJa: "サトイモ",
    familyJa: "サトイモ科",
    familyKey: "araceae",
    rotationYears: 4,
    sowMonths: [4, 5],
    harvestMonths: [9, 10, 11],
    companionGood: ["ショウガ", "エダマメ", "セロリ", "パセリ", "トウモロコシ"],
    companionBad: [],
    note: "連作障害が出やすく3〜4年あける。高温多湿を好み乾燥に弱い",
  },

  // ===== アオイ科 =====
  {
    id: "okra",
    nameJa: "オクラ",
    familyJa: "アオイ科",
    familyKey: "malvaceae",
    rotationYears: 2,
    sowMonths: [4, 5, 6],
    harvestMonths: [7, 8, 9, 10],
    companionGood: ["エダマメ", "ニラ", "マリーゴールド", "バジル"],
    companionBad: ["トマト", "ナス", "ピーマン", "ニンジン", "ダイコン"],
    note: "連作障害があり2〜3年あける。根菜・ナス科の近接はセンチュウ増で避ける",
  },

  // ===== バラ科 =====
  {
    id: "strawberry",
    nameJa: "イチゴ",
    familyJa: "バラ科",
    familyKey: "rosaceae",
    rotationYears: 2,
    sowMonths: [10, 11],
    harvestMonths: [4, 5, 6],
    companionGood: ["ニンニク", "ネギ", "ボリジ"],
    companionBad: ["ニラ"],
    note: "連作を嫌い2〜3年あける。秋植え→翌春収穫の一季なりが家庭菜園向き",
  },

  // ===== シソ科 =====
  {
    id: "shiso",
    nameJa: "シソ",
    familyJa: "シソ科",
    familyKey: "lamiaceae",
    rotationYears: 1,
    sowMonths: [4, 5, 6],
    harvestMonths: [6, 7, 8, 9, 10],
    companionGood: ["ナス", "サツマイモ"],
    companionBad: [],
    note: "連作障害は出にくい一年草。香りでナス等の害虫を忌避",
  },
  {
    id: "basil",
    nameJa: "バジル",
    familyJa: "シソ科",
    familyKey: "lamiaceae",
    rotationYears: 1,
    sowMonths: [4, 5],
    harvestMonths: [7, 8, 9, 10],
    companionGood: ["トマト", "ピーマン", "ナス"],
    companionBad: [],
    note: "トマトの定番コンパニオン。香りで害虫を忌避し生育を助ける",
  },
  {
    id: "mint",
    nameJa: "ミント",
    familyJa: "シソ科",
    familyKey: "lamiaceae",
    rotationYears: 0,
    sowMonths: [3, 4, 9, 10],
    harvestMonths: [5, 6, 7, 8, 9, 10],
    companionGood: ["キャベツ", "トマト", "ナス"],
    companionBad: [],
    note: "多年草で連作障害ほぼ無し。繁殖力が強く地植えは要根止め",
  },
]);

/** id → Crop の参照マップ。 */
const CROP_MAP = new Map(CROPS.map((c) => [c.id, c]));
/** familyKey → Family の参照マップ。 */
const FAMILY_MAP = new Map(FAMILIES.map((f) => [f.key, f]));

/**
 * @param {string} id
 * @returns {Crop | undefined}
 */
export function cropById(id) {
  return CROP_MAP.get(id);
}

/**
 * @param {string} key
 * @returns {Family | undefined}
 */
export function familyByKey(key) {
  return FAMILY_MAP.get(key);
}

/** UI のプルダウン用に、科ごとにまとめた作物リストを返す（FAMILIES の順）。 */
export function cropsGroupedByFamily() {
  return FAMILIES.map((f) => ({
    family: f,
    crops: CROPS.filter((c) => c.familyKey === f.key),
  })).filter((g) => g.crops.length > 0);
}
